version: '3.5'

services:
  api01: &api
    image: api-henry
    hostname: api01
    depends_on:
      - db
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "140MB"

  api02:
    <<: *api
    hostname: api02
    ports:
      - "8081:8080"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "20MB"

  db:
    image: postgres:latest
    restart: always
    hostname: db
    environment:
      - POSTGRES_USER=gungnir
      - POSTGRES_PASSWORD=gungnir
      - POSTGRES_DB=gungnir_db
    volumes:
      - ./sql/scripts/init/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: "250MB"

networks:
  default:
    driver: bridge
    name: garnize